name: Heroku push

on:
  push:
    branches:
      - main

jobs:
  heroku_git_push:
    runs-on: ubuntu-latest
    name: Push code to Heroku
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push code
        uses: yunojuno/heroku-git-push@improve-logging
        with:
          email: eddybrown@me.com
          api_key: ${{ secrets.HEROKU_PUSH_API_KEY }}
          app_names: |
            test-app-dev-123
            test-app-prod-123